services:
  tomcat:
    image: "service:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30000:30000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 40s
    networks:
      - library-net
    depends_on: 
      mysql: 
        condition: service_healthy
                
  mysql:
    image: "mysql:latest"
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 40s
      resources:
        limits:
          cpus: '2.0'
          memory: 4096M
        reservations:
          cpus: '1.0'
          memory: 2048M
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - library-net
networks:
  library-net: {}
volumes:
  mysql: {}