apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
type: Opaque
stringData: #this secret contains an attribute with a value that is a (SQL) script. This script will be mapped to a
#file in the mysql pod's containers when the secret is associated with a specific volume
  script.sql: "create user 'domcretan'@'%' identified by 'admin_root_kyr1';
grant all on *.* to 'domcretan'@'%' with grant option;
create database books;
connect books;
create table book(isbn VARCHAR(15) PRIMARY KEY, authors VARCHAR(100) NOT NULL, title VARCHAR(50) NOT NULL, publisher VARCHAR(20) NOT NULL, date VARCHAR(20), category VARCHAR(20), summary VARCHAR(100), language VARCHAR(15));
exit"